### ISSUE TITLE
Site Contributors - results not matching resources linked to

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#111]
The specific numbers of resources shown under each contributor doesn't correspond with actual results. When clicked there are much fewer resources shown and they are duplicated in the listing

**Comment by clararaubertas** [comment]
should be fixed!

**Comment by sbxchicago** [comment]
This has changed for the better but some numbers are still not correct.

**Comment by clararaubertas** [comment]
This issue should be fixed!
