### ISSUE TITLE
Labeling with initial caps - header/footer, elsewhere

### ISSUE THREAD

**Issue by sbxchicago** [betterscientificsoftware/betterscientificsoftware.github.io#200]
We are planning on employing consistency across the site, in terms of what gets caps. In titles we ALWAYS want initial caps on every word in the title. There's places where we need your help to do this. 

Header: 
Contribute To BSSw

Footer:
Follow Our RSS Feed

Home:
Resources For Developer Productivity And Software Sustainability

Blog: 
Subscribe To Our Email Digest

Category pages (Better Planning, Better Development, Better Performance, etc.)
For topics > See All XX Resources

**Comment by clararaubertas** [comment]
Fixed!

**Comment by sbxchicago** [comment]
In Header, can we lower case the "w" in: Contribute To BSSw 

and

Category pages (Better Planning, Better Development, Better Performance, etc.)
in topic links I'm still seeing initial lower case, should be: See All XX Resources

**Comment by clararaubertas** [comment]
Should be fixed!
